### ISSUE TITLE
Login Failed not showing

### ISSUE THREAD

**Issue by richnsim** [djlauk/tecla-php#73] opened 2020-07-01 06:50 UTC
**What I did**
Log in with invalid password or user

**What happened**
I got a blanc browser page

**What should have happened**
Error message: "Wrong password..."

**Comment by richnsim** [comment] 2020-07-01 06:51
Can't reproduce... Was this just fixed right now?

**Comment by djlauk** [comment] 2020-07-01 07:36
Nope. Maybe that one time the blank page showed up, it was a glitch in the network connection of the browser. I often have web pages not load when the WiFi or VPN has "a hiccup".

The login error message has already been in place for a long time, and I, too, cannot reproduce it.

I hence close this issue, but feel free to re-open if the problem reappears.

**Closed as completed** 2020-07-01 07:36 UTC
Labels: wontfix
